### ISSUE TITLE
Basic HWND usage tries to link to DPI aware functions since 0.0.22

### ISSUE THREAD

**Issue by TRPB** [rodrigocfd/winsafe#178]
If anything uses HWND winsafe tries to link to DPI aware functions which are for some reason not available in mingw32. 

I am very much a novice here but this code works fine with winsafe 0.0.21:

```rust
#![windows_subsystem = "windows"]

use winsafe::{self as w, prelude::*};
fn main() -> w::AnyResult<()> {
    w::HWND::NULL.MessageBox("Hello World", "Test Application", w::co::MB::OK)?;
    Ok(())
}
```

On any more recent versions the build fails with:

```
undefined reference to `GetWindowDpiHostingBehavior'

```

There's probably a bigger issue here with mingw32 missing the headers but that code shouldn't need to access anything rendering related to display a message box and likely this will cause an unnecessarily large executable even if it did work.

Winsafe should decouple HWND from anything rendering related.

My shell.nix for building:

```nix
{
  pkgs ? import <nixpkgs> { },
}:
pkgs.mkShell {
  nativeBuildInputs = with pkgs; [
    gcc
    rustfmt
    clippy
    pkgsCross.mingwW64.stdenv.cc
    pkgsCross.mingwW64.windows.mingw_w64
    pkgsCross.mingwW64.windows.pthreads
    pkgsCross.mingwW64.windows.mingw_w64_headers
    rustup
    clang
    llvm
  ];

  CARGO_TARGET_X86_64_PC_WINDOWS_GNU_LINKER = "${pkgs.pkgsCross.mingwW64.stdenv.cc}/bin/x86_64-w64-mingw32-gcc";
  CARGO_TARGET_X86_64_PC_WINDOWS_GNU_AR = "${pkgs.pkgsCross.mingwW64.stdenv.cc}/bin/x86_64-w64-mingw32-ar";

  shellHook = ''
    rustup default stable
    rustup target add x86_64-pc-windows-gnu
  '';
}
```

edit: `use windows::Win32::UI;` does fix it but as expected makes the executable much larger due to the significant extra dependency
